CUR_PATH		:= $(shell pwd)
HOME_PATH		:= $(abspath $(CUR_PATH)/../../../../..)

include $(HOME_PATH)/build/config.mak

BASE_PATH		:= $(HOME_PATH)/msp/component
SRC_PATH		:= $(CUR_PATH)
PRJ_OUT_HOME		:= $(HOME_PATH)/build/out/$(PROJECT)
OBJ_OUT_PATH		:= $(PRJ_OUT_HOME)/objs
OUT_PATH		:= $(MSP_OUT_PATH)
SRC_RELATIVE_PATH	:= $(subst $(HOME_PATH)/,,$(SRC_PATH))
TARGET_OUT_PATH		:= $(OBJ_OUT_PATH)/$(SRC_RELATIVE_PATH)
SYS_LIB_PATH		:= $(MSP_OUT_PATH)/lib

SRC_I2C_PATH		:= $(BASE_PATH)/isp_proton/sensor/i2c
SNS_PATH		:= $(BASE_PATH)/isp_proton/sensor
COMMON_PATH		:= $(BASE_PATH)/isp_proton/sensor/common
COMMON_SRC_PATH		:= $(BASE_PATH)/isp_proton/sensor/common/src
MIPI_SWITH_SRC_PATH	:= $(BASE_PATH)/isp_proton/sensor/mipi_switch

GENERATED_PATH		:= $(TARGET_OUT_PATH)/generated
PARAMS_PATH		:= $(SNS_PATH)/smartsens_sc200ai/params_file/ax620e
soversion=yes

MOD_NAME		:= sns_sc035hgs
OUTPUT			:= $(TARGET_OUT_PATH)/.obj

SRCS			+= $(wildcard $(SRC_I2C_PATH)/*.c) \
			   $(wildcard $(MIPI_SWITH_SRC_PATH)/*.c) \
			   $(wildcard $(CUR_PATH)/*.c) \
			   $(wildcard $(COMMON_SRC_PATH)/*.c)

CINCLUDE		+= -I$(SRC_I2C_PATH)/ \
			   -I$(MIPI_SWITH_SRC_PATH)/ \
			   -I$(OUT_PATH)/include \
			   -I$(SNS_PATH)/include \
			   -I$(COMMON_PATH)/include \
			   -I$(PARAMS_PATH) \
			   -I$(GENERATED_PATH)

OBJS			:= $(SRCS:%.c=$(OUTPUT)/%.o)
DEPS			:= $(OBJS:%.o=%.d)

SONAME			:= lib$(MOD_NAME).so
STRIPPED_TARGET		:= $(SONAME)
DEBUG_TARGET		:= lib$(MOD_NAME).debug

CFLAGS			:= ${DYNAMIC_FLAG}
ifeq ($(debug),yes)
CFLAGS			+= -Werror -Wall -O0 -g
else
CFLAGS			+= -Wall -Werror -O2 -ggdb3
endif
CFLAGS			+= -Wno-unused-variable
CFLAGS			+= -DLINUX
CFLAGS			+= -fvisibility=hidden
CFLAGS			+= -DUSE_DEFAULT_PARAM

CLIB			+= -lpthread

INSTALL_LIB		:= $(STRIPPED_TARGET) $(DEBUG_TARGET)
MV_TARGET		:= $(INSTALL_LIB)

LINK = $(CC)

include $(HOME_PATH)/build/rules.mak
